apiVersion: 1.0.0
metadata:
  generateName: java-openliberty
attributes:
  odo.autorestart: "false"
projects:
  - name: user-app
    source:
      type: git
      location: 'https://github.com/OpenLiberty/application-stack.git'
      sparseCheckoutDir: /templates/default
components:
- type: chePlugin
  id: redhat/java/latest
  memoryLimit: 1512Mi
- alias: devruntime
  mountSources: true
  type: dockerimage
  # this custom image source can be found in the baseimage section of the repo at:
  # https://github.com/OpenLiberty/application-stack.git
  image: ajymau/java-openliberty-odo:0.1
  memoryLimit: 1512Mi
  endpoints:
  - name: 9080/tcp
    port: 9080
  - name: 9443/tcp
    port: 9443
commands:
  - name: devInit
    actions:
      - workdir: /projects/user-app
        type: exec
        command: echo "moving liberty" && mkdir -p /projects/user-app/target/liberty && mv /opt/ol/wlp /projects/user-app/target/liberty
        component: devruntime
  - name: devBuild
    actions:
      - workdir: /projects/user-app
        type: exec
        command: if [ -e /projects/user-app/.disable-bld-cmd ];
                 then
                     echo "found the disable file" && echo "devBuild command will not run" && exit 0;
                 else
                     echo "will run the devBuild command" && mvn -Dmaven.repo.local=/mvn/repository package && touch ./.disable-bld-cmd;
                 fi
        component: devruntime
  - name: devRun
    actions:
      - workdir: /projects/user-app
        type: exec
        command: mvn -Dmaven.repo.local=/mvn/repository -Dliberty.runtime.version=20.0.0.6 -DhotTests=true liberty:dev
        component: devruntime
    attributes:
        restart: "false"
