apiVersion: 1.0.0
metadata:
  name: openLiberty
attributes:
  odo.autorestart: "false"
projects:
  - name: user-app 
    source:
      type: git
      location: 'https://github.com/OpenLiberty/application-stack.git'
      sparseCheckoutDir: /templates/default
components:
  - id: redhat/java/latest
    memoryLimit: 1512Mi
    type: chePlugin
- alias: devruntime
  mountSources: true
  type: dockerimage
  image: kabanero/ubi8-maven:0.3.1 
  memoryLimit: 1512Mi
  volumes:
  - name: m2
    containerPath: /home/user/.m2
    endpoints:
  - name: 9080/tcp
    port: 9080
  - name: 9443/tcp
    port: 9443
commands:
  - name: devInit
    actions:
      - workdir: /projects/user-app
        type: exec
        command: mvn -B liberty:install-server liberty:create liberty:install-feature dependency:go-offline
        component: devruntime 
  - name: devBuild
    actions:
      - workdir: /projects/user-app
        type: exec
        command: if [ -e /projects/user-app/.disable-bld-cmd ]; 
                 then 
                     echo "found the disable file" && echo "devBuild command will not run" && exit 0; 
                 else
                     echo "will run the devBuild command" && mvn package && touch ./.disable-bld-cmd;
                 fi 
        component: devruntime 
  - name: devRun
    actions:
      - workdir: /projects/user-app
        type: exec
        command: mvn -DhotTests=true liberty:dev
        component: devruntime 
    attributes:
        restart: "false"
